name: build

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: npm install and build
      run: |
        npm install
        npm run build:production
      env:
        CI: true

    - name: Clean files
      run: |
        rm -R img
        rm -R src
        rm tsconfig.json
        rm webpack.config.js
        rm webpack.prod.js

    - name: Init git
      env:
        WT_DATA_WEB_PRIVATE: ${{ secrets.WT_DATA_WEB_PRIVATE }}
      run: |
        mkdir -p ~/.ssh/
        echo "$WT_DATA_WEB_PRIVATE" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.email "smczx@hotmail.com"
        git config --global user.name "ControlNet"
        git remote add origin-ssh git@github.com:ControlNet/wt-data-project.web.git

    - name: Commit and push
      run: |
        git add -A
        git commit -m "update"
        git push origin-ssh HEAD:web -f
